### ISSUE TITLE
Run all tests on latest build of 2sxc ca. 9.33

### ISSUE THREAD

**Issue by iJungleboy** [2sic/app-dev-testing-permissions-rest#2]

**Comment by tvatavuk** [comment]
- all tests executed as expected (all is green) while testing last version of 2sxc (ca. 9.33) for all test users

![image](https://user-images.githubusercontent.com/2724850/46019957-8666f580-c0dd-11e8-8887-e2d98e58833c.png)

**Comment by iJungleboy** [comment]
100% ??? that's awesome! thx
